### ISSUE TITLE
Expected signal to be an instanceof AbortSignal

### ISSUE THREAD

**Issue by RishikeshDarandale** [auth0/auth0-react#323]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

> Provide a clear and concise description of the issue

I am using `apollo-client` @ 2.6 as graphql client with `isomorphic-fetch` @ 3.0.0 to support client side and server side calls. 

Sample graphql client code with 
```
import * as fetch from "isomorphic-fetch";
...

const client = new ApolloClient({
  ...
  link: new HttpLink({
     fetch,
     ...
  });
});
```

When I add `auth-react` to the project, graphql calls fails on server side with following error:

```
Error: Network error: Expected signal to be an instanceof AbortSignal
  at new ApolloError (/home/projects/my-web-app/node_modules/apollo-client/bundle.umd.js:92:26)
  at /home/projects/my-web-app/node_modules/apollo-client/bundle.umd.js:1588:34
  ...
```

When, I remove the `auth0-react`, then it works without an issue.

### What was the expected behavior?

> Tell us about the behavior you expected to see

Adding `auth0-react` should not break existing functionality.

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

- Setup a react app with CSR and SSR feature to render the data from graphql api
- Test everything works fine.
- Add dependency `auth-react` and verify the functionality
- SSR calls to graphql api fails with error mentioned above.

**Can the behavior be reproduced using the [React SDK Playground](https://github.com/auth0/auth0-react/blob/master/CONTRIBUTING.md#local-development)?**

If so, provide steps:

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - `clientId` and `domain` (these are publicly available)
> - Screenshots

### Environment

> Please provide the following:

- **Version of `auth0-react` used:** 1.8.0
- **Which browsers have you tested in?** chrome, firefox
- **Which framework are you using, if applicable (Angular, React, etc):** react 16.8
- **Other modules/plugins/libraries that might be involved:** apollo client 2.6.x

### References

- https://github.com/apollographql/apollo-client/issues/6765

**Comment by adamjmcgrath** [comment]
Hi @RishikeshDarandale - thanks for raising this.

The underlying library (auth0-spa-js) uses `abortcontroller-polyfill` which doesn't play nicely with `node-fetch@2`.  eg

```js
require('@auth0/auth0-react');
(async () => {
  const controller = new AbortController();
  const { default: fetch } = await import('node-fetch'); // v2
  await fetch('https://reqres.in/api/user', { signal: controller.signal });
})();

// 💥  TypeError: Expected signal to be an instanceof AbortSignal
```

You have a couple of options:

1. **follow the advice in the `abortcontroller-polyfill` docs https://github.com/mo/abortcontroller-polyfill#using-it-on-nodejs**

```js
const { abortableFetch } = require('abortcontroller-polyfill/dist/cjs-ponyfill');
require('@auth0/auth0-react');

(async () => {
  const controller = new AbortController();
  const { fetch } = abortableFetch((await import('node-fetch')).default);
  await fetch('https://reqres.in/api/user', { signal: controller.signal });
})();

// 👍 
```

2. **upgrade to node-fetch@3**
3. **upgrade your version of Node to >= 15**

In a future major we will look at modernising spa-js with regards to it's polyfil usage, but this wont happen for a while

**Comment by RishikeshDarandale** [comment]
Thanks @adamjmcgrath for a quick reply, So my guess was correct about the `polyfill` used in `spa-js`.

Unfortunately :( , we use `isomorphic-fetch` which internally users `node-fetch`, thus first two solutions will depend on the `isomorphic-fetch`.

We use aws lambda and it's not supporting `16-LTS`. AWS lambda has max `14-LTS`!

**Comment by adamjmcgrath** [comment]
Hi @RishikeshDarandale - you should still be able to use `abortableFetch` with `isomorphic-fetch` - since it should just be aliasing `node-fetch` (in a node environment at least), so something like the following should work:

```js
import * as fetch from "isomorphic-fetch";
import { abortableFetch } from "abortcontroller-polyfill/dist/cjs-ponyfill";

...

const client = new ApolloClient({
  ...
  link: new HttpLink({
     fetch: abortableFetch(fetch).fetch, 
     ...
  });
});
```

**Comment by RishikeshDarandale** [comment]
Thanks @adamjmcgrath , this is working like a charm!

> Hi @RishikeshDarandale - you should still be able to use `abortableFetch` with `isomorphic-fetch` - since it should just be aliasing `node-fetch` (in a node environment at least), so something like the following should work:
> 
> ```js
> import * as fetch from "isomorphic-fetch";
> import { abortableFetch } from "abortcontroller-polyfill/dist/cjs-ponyfill";
> 
> ...
> 
> const client = new ApolloClient({
>   ...
>   link: new HttpLink({
>      fetch: abortableFetch(fetch).fetch, 
>      ...
>   });
> });
> ```
