### ISSUE TITLE
GitHub authentication is broken on Android devices with Chrome browser.

### ISSUE THREAD

**Issue by aiven715** [auth0/auth0-react#353]
### Describe the problem

We're using GitHub social authentication in our React app.

When a user tries to log in to the application from an Android device with a Chrome browser, the authentication process fails. The issue only happens when the user has a GitHub application installed on his device. Seems like the application happens to be in the middle of the process, which affects the authentication flow.

The following error happens in the browser console when the authentication fails:
```
Error: Invalid state
  at call(webpack://_N_E/../node_modules/@auth0/auth0-react/dist/auth0-react.esm.js:107:80010)
  at ? (webpack://_N_E/../node_modules/@auth0/auth0-react/dist/auth0-react.esm.js:107:2248)
  at next(webpack://_N_E/../node_modules/@auth0/auth0-react/dist/auth0-react.esm.js:107:1564)
  at ? (webpack://_N_E/../node_modules/@auth0/auth0-react/dist/auth0-react.esm.js:107:1289)
  at new Promise(<anonymous>)
  at o(webpack://_N_E/../node_modules/@auth0/auth0-react/dist/auth0-react.esm.js:107:1028)
  at handleRedirectCallback(webpack://_N_E/../node_modules/@auth0/auth0-react/dist/auth0-react.esm.js:107:79426)
  at call(webpack://_N_E/../node_modules/@auth0/auth0-react/dist/auth0-react.esm.js:243:53)
  at step(webpack://_N_E/../node_modules/@auth0/auth0-react/dist/auth0-react.esm.js:87:23)
  at next(webpack://_N_E/../node_modules/@auth0/auth0-react/dist/auth0-react.esm.js:68:53)
  at ? (webpack://_N_E/../node_modules/@auth0/auth0-react/dist/auth0-react.esm.js:61:71)
  at new Promise(<anonymous>)
  at __awaiter(webpack://_N_E/../node_modules/@auth0/auth0-react/dist/auth0-react.esm.js:57:12)
  at h(webpack://_N_E/../node_modules/@auth0/auth0-react/dist/auth0-react.esm.js:236:31)
  at fk(webpack://_N_E/../node_modules/react-dom/cjs/react-dom.production.min.js:262:359)
  at Nf(webpack://_N_E/../node_modules/scheduler/cjs/scheduler.production.min.js:18:343)
  at gg(webpack://_N_E/../node_modules/react-dom/cjs/react-dom.production.min.js:122:325)
  at Oj(webpack://_N_E/../node_modules/react-dom/cjs/react-dom.production.min.js:261:308)
  at Lj(webpack://_N_E/../node_modules/react-dom/cjs/react-dom.production.min.js:243:50)
  at b(webpack://_N_E/../node_modules/react-dom/cjs/react-dom.production.min.js:123:115)
  at Nf(webpack://_N_E/../node_modules/scheduler/cjs/scheduler.production.min.js:18:343)
  at gg(webpack://_N_E/../node_modules/react-dom/cjs/react-dom.production.min.js:122:325)
  at jg(webpack://_N_E/../node_modules/react-dom/cjs/react-dom.production.min.js:123:61)
  at ig(webpack://_N_E/../node_modules/react-dom/cjs/react-dom.production.min.js:122:428)
  at Jg(webpack://_N_E/../node_modules/react-dom/cjs/react-dom.production.min.js:237:203)
  at lk(webpack://_N_E/../node_modules/react-dom/cjs/react-dom.production.min.js:285:27)
  at tk(webpack://_N_E/../node_modules/react-dom/cjs/react-dom.production.min.js:289:150)
  at render(webpack://_N_E/../node_modules/react-dom/cjs/react-dom.production.min.js:296:69)
  at renderReactElement(webpack://_N_E/../node_modules/next/dist/client/index.js:483:31)
  at doRender(webpack://_N_E/../node_modules/next/dist/client/index.js:665:5)
  at call(webpack://_N_E/../node_modules/next/dist/client/index.js:375:19)
  at tryCatch(webpack://_N_E/../node_modules/regenerator-runtime/runtime.js:63:40)
  at _invoke(webpack://_N_E/../node_modules/regenerator-runtime/runtime.js:294:22)
  at key(webpack://_N_E/../node_modules/regenerator-runtime/runtime.js:119:21)
  at asyncGeneratorStep(webpack://_N_E/../node_modules/next/dist/client/index.js:28:24)
  at _next(webpack://_N_E/../node_modules/next/dist/client/index.js:46:17)
  at ? (webpack://_N_E/../node_modules/next/dist/client/index.js:51:13)
  at new Promise(<anonymous>)
  at apply(webpack://_N_E/../node_modules/next/dist/client/index.js:43:16)
  at render(webpack://_N_E/../node_modules/next/dist/client/index.js:396:20)
  at sub(webpack://_N_E/../node_modules/next/dist/client/index.js:334:48)
  at notify(webpack://_N_E/../node_modules/next/dist/shared/lib/router/router.js:1060:21)
  at set(webpack://_N_E/../node_modules/next/dist/shared/lib/router/router.js:878:21)
  at call(webpack://_N_E/../node_modules/next/dist/shared/lib/router/router.js:730:24)
  at tryCatch(webpack://_N_E/../node_modules/regenerator-runtime/runtime.js:63:40)
  at _invoke(webpack://_N_E/../node_modules/regenerator-runtime/runtime.js:294:22)
  at key(webpack://_N_E/../node_modules/regenerator-runtime/runtime.js:119:21)
  at asyncGeneratorStep(webpack://_N_E/../node_modules/next/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:20)
  at _next(webpack://_N_E/../node_modules/next/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
```

The issue is applicable specifically to Chrome browser on the Android devices. Other browsers such as Firefox, Bromite (Chrome fork) work correctly.

### Environment

- **Version of `auth0-react` used:** 1.10.0
- **Which browsers have you tested in?** Google Chrome on Android
- **Which framework are you using, if applicable (Angular, React, etc):** React

**Comment by adamjmcgrath** [comment]
Hi @aiven715 - thanks for raising this

Does the user end up on a different tab in this scenario? If so, you could try using the  [useCookiesForTransactions](https://auth0.github.io/auth0-spa-js/interfaces/auth0clientoptions.html#usecookiesfortransactions) option

```jsx
<Auth0Provider
    ...
     useCookiesForTransactions={true}
  >
    <App />
  </Auth0Provider>,
```

**Comment by adamjmcgrath** [comment]
Hi @aiven715  - closing due to inactivity.

Ping me if you want to reopen

**Comment by aiven715** [comment]
@adamjmcgrath yes, it fixed the issue. Thanks for the assistance!
