### ISSUE TITLE
Cannot build my project

### ISSUE THREAD

**Issue by aleguern** [auth0/auth0-react#510]
I'm trying to build my vite project using auth0 and react. 

When I build I get the following error : 
```
[commonjs--resolver] Unexpected token (58:108) in /node_modules/@auth0/auth0-react/dist/auth0-react.esm.js
file: ...node_modules/@auth0/auth0-react/dist/auth0-react.esm.js:58:108
56: 
57: function __awaiter(thisArg, _arguments, P, generator) {
58:     function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value) })}
                                                                                                                ^
59:     return new (P || (P = Promise))(function (resolve, reject) {
60:         function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
error during build:
SyntaxError: Unexpected token (58:108) in ...node_modules/@auth0/auth0-react/dist/auth0-react.esm.js
    at pp$4.raise (file://...node_modules/rollup/dist/es/shared/rollup.js:20533:13)
    at pp$9.unexpected (file://...node_modules/rollup/dist/es/shared/rollup.js:17834:8)
    at pp$5.parseIdent (file://...node_modules/rollup/dist/es/shared/rollup.js:20464:10)
    at pp$7.parseBindingAtom (file://...node_modules/rollup/dist/es/shared/rollup.js:19093:15)
    at pp$7.parseMaybeDefault (file://...node_modules/rollup/dist/es/shared/rollup.js:19128:23)
    at pp$5.parsePropertyValue (file://...node_modules/rollup/dist/es/shared/rollup.js:20212:35)
    at pp$5.parseProperty (file://...node_modules/rollup/dist/es/shared/rollup.js:20203:8)
    at pp$5.parseObj (file://...node_modules/rollup/dist/es/shared/rollup.js:20158:21)
    at pp$7.parseBindingAtom (file://...node_modules/rollup/dist/es/shared/rollup.js:19090:19)
    at pp$7.parseMaybeDefault (file://...node_modules/rollup/dist/es/shared/rollup.js:19128:23)
```

I am using auth0 "@auth0/auth0-react": "2.0.0" and vite "vite": "^4.1.0"

**Comment by ewanharris** [comment]
Hey @aleguern, I just tested using auth0-react in a freshly created [react-ts](https://github.com/vitejs/vite/tree/main/packages/create-vite/template-react-ts) template from create-vite and was able to run locally and build the project. Could you please provide a minimal sample that reproduces this issue so we can investigate if this is an issue on our end?

**Comment by adamjmcgrath** [comment]
Closing due to inactivity
