### ISSUE TITLE
auth0-react and next.js

### ISSUE THREAD

**Issue by tomleeson** [auth0/auth0-react#64]
Hello there, 

We have recently switched over from auth0-spa to auth0-react in our next.js/node server project. I've noticed a number of these exceptions being reported in our application insights when a user logs into the application: 

ReferenceError: window is not defined

Callstack: 
at Ar (/home/site/wwwroot/node_modules/@auth0/auth0-react/dist/auth0-react.cjs.js:114:43293)
at _r (/home/site/wwwroot/node_modules/@auth0/auth0-react/dist/auth0-react.cjs.js:114:39556)
at e.<anonymous> (/home/site/wwwroot/node_modules/@auth0/auth0-react/dist/auth0-react.cjs.js:114:59060)
at /home/site/wwwroot/node_modules/@auth0/auth0-react/dist/auth0-react.cjs.js:114:2077
at Object.next (/home/site/wwwroot/node_modules/@auth0/auth0-react/dist/auth0-react.cjs.js:114:2186)
at /home/site/wwwroot/node_modules/@auth0/auth0-react/dist/auth0-react.cjs.js:114:1118
at o (/home/site/wwwroot/node_modules/@auth0/auth0-react/dist/auth0-react.cjs.js:114:886)
at e.buildAuthorizeUrl (/home/site/wwwroot/node_modules/@auth0/auth0-react/dist/auth0-react.cjs.js:114:58874)
at e.<anonymous> (/home/site/wwwroot/node_modules/@auth0/auth0-react/dist/auth0-react.cjs.js:114:61293)

It's important to note that the user is not seeing any error messages in the browser console, and no errors are shown in the UI. This seems to be an issue with nextjs server side rendering. 

I can provide any more details and answer more questions as needed.

**Comment by adamjmcgrath** [comment]
Hi @tomleeson 

I see `buildAuthorizeUrl` in your call stack, which tells me that the application is calling `loginWithRedirect` (or `loginWithPopup`) while server side rendering, which will fail with `ReferenceError: window is not defined`

Are you calling either of those login methods in your application from a place that might be triggered during server side rendering? (it should only be called in a `useEffect`, a click handler or some code that's guarded by `if typeof window !== 'undefined'`)

**Comment by tomleeson** [comment]
That was exactly the issue. Thanks!
